//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_STUDENT
    {
        public int STUTYPE_ID { get; set; }
        public string TYPE_NAME { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
